### PR TITLE
Update to handle non-custom reports via direct url

### PR DESCRIPTION
**Pull request by FTremain**

### CODE REVIEW

**Comment by pocin** [comment]
Hi Francis, thanks for the PR!
Please edit the readme.md as well to reflect the changes so we have an idea how to use the new feature properly.

Regarding the actual implementation - it would be better to implement the `"direct_url"` action in a separate method, but if it works  for you (and it didn't break existing behavior) I won't wont be a dog about that.

**Comment by pocin** [comment]
@FTremain When you give me a green and you have everything tested I will merge this PR and it will propagate to keboola almost instantly + don't forget about the readme! :-)

**Comment by FTremain** [comment]
@pocin Hey! Just found a bug if I don't use the account id. Will let you know once I have fixed this, should be in an hour or 2 just testing a fix now then will be back to doing the readme. Do I just push it to my repo then this pull req will merge the further commits after I sumitted the req?

**Comment by pocin** [comment]
Ok! Just push every commit as you have been doing so far. I will merge the pr and take care of rest.

**Comment by FTremain** [comment]
@pocin Done. Should be done now. Is the readme good enough?

**Comment by pocin** [comment]
If it's good enough for you it's good enough for me :-) The image should be live in keboola. Let me know if there are any issues.

**Pull request merged**
